---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo 'init script' # runs during prebuild
      python -m venv .venv
      source .venv/bin/activate
      pip install robotframework robotframework-browser robotframework-requests pyotp
      rfbrowser init
    command: |
      echo 'start script'
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode